# /// script
# dependencies = ["pyyaml"]
# ///
"""Generate dbt reference seeds (code,display) from cdm/enums.yaml.

One seed per enum that carries display labels, written to
  <root>/seeds/mapping/seed_<entity>.csv
plus a single seeds_mapping.yml (dbt seed properties) describing them all.

All enums are generated automatically - no hand-maintained list. 
Code only enums with no descriptions are skipped.

Seeds mirror the UK Core / HL7 CodeSystems captured in enums.yaml, so the dbt
lookups never drift from the enums / from UK Core.

Usage:  uv run scripts/generate_dbt_seeds.py [OUTPUT_ROOT]   (default: dbt_metadata/)
"""
from __future__ import annotations

import csv
import re
import sys
from pathlib import Path

import yaml

REPO = Path(__file__).parent.parent
ENUMS = REPO / "cdm" / "enums.yaml"
SEED_PREFIX = "seed_"   # change to e.g. "seed_nhs__" to add a source segment


def one_line(text):
    return " ".join((text or "").split())


def snake(enum_name: str) -> str:
    base = re.sub(r"Enum$", "", enum_name)
    return re.sub(r"(?<!^)(?=[A-Z])", "_", base).lower()


def pv_rows(pv: dict) -> list[tuple[str, str]]:
    rows = []
    for code, meta in (pv or {}).items():
        display = meta.get("description", "") if isinstance(meta, dict) else ""
        rows.append((str(code), display))
    return rows


def main(outroot: Path) -> None:
    enums = yaml.safe_load(ENUMS.read_text(encoding="utf-8"))["enums"]
    outdir = outroot / "seeds" / "mapping"
    outdir.mkdir(parents=True, exist_ok=True)

    props = []
    for enum_name, spec in enums.items():
        rows = pv_rows(spec.get("permissible_values"))
        if not any(display for _, display in rows):
            continue  # code-only enum - nothing to map
        seed_name = SEED_PREFIX + snake(enum_name)
        with open(outdir / f"{seed_name}.csv", "w", newline="", encoding="utf-8") as f:
            w = csv.writer(f)
            w.writerow(["code", "display"])
            w.writerows(rows)
        props.append((seed_name, one_line(spec.get("description", ""))))
        print(f"  wrote seeds/mapping/{seed_name}.csv  ({len(rows)} rows)")

    doc = {"seeds": [
        {
            "name": name,
            "description": desc,
            "config": {"column_types": {"code": "varchar", "display": "varchar"}},
            "columns": [
                {"name": "code", "description": "Code value (join key)."},
                {"name": "display", "description": "Human readable label for the code."},
            ],
        }
        for name, desc in props
    ]}
    with open(outdir / "seeds_mapping.yml", "w", encoding="utf-8") as f:
        f.write(
            "# AUTO-GENERATED by the target-common-data-model (CDM) spec repo - DO NOT EDIT.\n"
            "# Source of truth: cdm/enums.yaml in that repo. Regenerate there; edits here are overwritten.\n"
        )
        yaml.safe_dump(doc, f, sort_keys=False, default_flow_style=False, allow_unicode=True, width=100)
    print(f"  wrote seeds/mapping/seeds_mapping.yml  ({len(props)} seeds)")


if __name__ == "__main__":
    out = Path(sys.argv[1]) if len(sys.argv) > 1 else REPO / "dbt_metadata"
    main(out)
